# This file was generated by GoReleaser. DO NOT EDIT.
cask "routeup" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "8a51d90b0455243e740e5513148e1f256c7cb052d7649e09e348b16feada930c"
      url "https://github.com/mukul-mehta/routeup/releases/download/v#{version}/routeup_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "aa8b94181f229e427fb3dc811e825e76eaef3df3c679bc4cfcc4c4fc72b4be05"
      url "https://github.com/mukul-mehta/routeup/releases/download/v#{version}/routeup_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5750ee4207feae3181c58118b5a9d5e8e8692ea1ec624c4d38209aef1aa77ec4"
      url "https://github.com/mukul-mehta/routeup/releases/download/v#{version}/routeup_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ab6e932d2cb1fa9938853d5c287d47edb694ce1632c15c9550bc8811e95d0329"
      url "https://github.com/mukul-mehta/routeup/releases/download/v#{version}/routeup_linux_arm64.tar.gz"
    end
  end

  name "routeup"
  desc "Stable HTTPS route names for local services"
  homepage "https://github.com/mukul-mehta/routeup"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "routeup"

  # No zap stanza required

  caveats <<~EOS
    Run `routeup setup` once to create and trust a local CA and bind port 443:
      routeup setup
  EOS
end
