# This file was generated by GoReleaser. DO NOT EDIT.
cask "routeup" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "e12773dbfd320f17bb0a9c479755f1ad9cd702d5c58e40808cba7ace8f48b2b1"
      url "https://github.com/mukul-mehta/routeup/releases/download/v#{version}/routeup_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "80c2ffb659594b9bd0573b62c7531d84e50257e150f809502e45809fd936d876"
      url "https://github.com/mukul-mehta/routeup/releases/download/v#{version}/routeup_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0812ab638621b6c46c78d9eae5985141fdb6e066ce023fef52dbd210ac596b05"
      url "https://github.com/mukul-mehta/routeup/releases/download/v#{version}/routeup_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "350902a0bb2ca6c54ce39efeb04be50649b3175cabf8af5d89ebc04297b2d1b3"
      url "https://github.com/mukul-mehta/routeup/releases/download/v#{version}/routeup_linux_arm64.tar.gz"
    end
  end

  name "routeup"
  desc "Stable HTTPS route names for local services"
  homepage "https://github.com/mukul-mehta/routeup"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "routeup"

  # No zap stanza required

  caveats <<~EOS
    Run `routeup setup` once to create and trust a local CA and bind port 443:
      routeup setup
  EOS
end
